import type { Client } from "@notionhq/client";
import type { BriefData } from "./research.js";

type BlockParam = Parameters<Client["blocks"]["children"]["append"]>[0]["children"][number];

function heading2(text: string): BlockParam {
	return {
		type: "heading_2",
		heading_2: { rich_text: [{ type: "text", text: { content: text } }] },
	};
}

function paragraph(text: string): BlockParam {
	return {
		type: "paragraph",
		paragraph: { rich_text: [{ type: "text", text: { content: text } }] },
	};
}

function callout(text: string, emoji: string, color: string): BlockParam {
	return {
		type: "callout",
		callout: {
			rich_text: [{ type: "text", text: { content: text } }],
			icon: { type: "emoji", emoji: emoji as "🟢" },
			color: color as "green_background",
		},
	};
}

function divider(): BlockParam {
	return { type: "divider", divider: {} };
}

function buildScoreBar(score: number): string {
	const filled = "█".repeat(score);
	const empty = "░".repeat(10 - score);
	return `${filled}${empty} ${score}/10`;
}

export async function createDecisionBrief(
	notion: Client,
	opportunityPageId: string,
	opportunityName: string,
	brief: BriefData,
	cost: number,
	parentPageId: string,
): Promise<string> {
	const isApprove = brief.recommendation === "Approve";
	const recEmoji = isApprove ? "✅" : "❌";
	const recColor = isApprove ? "green_background" : "red_background";
	const confidenceLabel = `Confidence: ${brief.confidence}`;

	const similarBetsText =
		brief.similarPastBets.length > 0
			? brief.similarPastBets
					.map(
						(b) =>
							`• ${b.name} — ${b.decision} — $${b.amount.toLocaleString()} — ` +
							`Score: ${b.outcomeScore ?? "N/A"} — Stars: ${b.starsData != null ? `+${b.starsData}` : "N/A"}\n  ${b.notes}`,
					)
					.join("\n\n")
			: "No comparable past decisions found.";

	const blocks: BlockParam[] = [
		callout(
			`${recEmoji}  RECOMMENDATION: ${brief.recommendation.toUpperCase()}  |  ${confidenceLabel}`,
			recEmoji as "✅",
			recColor,
		),
		divider(),
		heading2("Event Summary"),
		paragraph(brief.eventSummary),
		divider(),
		heading2("Audience Fit"),
		paragraph(`Score: ${buildScoreBar(brief.audienceFitScore)}`),
		paragraph(brief.audienceFitReason),
		paragraph(`Estimated reach: ${brief.estimatedReach}`),
		divider(),
		heading2("Budget Impact"),
		paragraph(`Cost: $${cost.toLocaleString()}`),
		paragraph(brief.budgetImpact),
		divider(),
		heading2("Similar Past Bets"),
		paragraph(similarBetsText),
		divider(),
		heading2("Reasoning"),
		paragraph(brief.reasoning),
		divider(),
		paragraph("Generated by Compass · Mark this opportunity Approved or Rejected in the Inbox to proceed."),
	];

	const page = await notion.pages.create({
		parent: { page_id: parentPageId },
		icon: { type: "emoji", emoji: recEmoji as "✅" },
		properties: {
			title: {
				title: [{ text: { content: `Decision Brief: ${opportunityName}` } }],
			},
		},
		children: blocks,
	});

	const pageUrl = `https://notion.so/${page.id.replace(/-/g, "")}`;

	await notion.pages.update({
		page_id: opportunityPageId,
		properties: {
			Status: { select: { name: "Decision Ready" } },
			"Brief Page/Event Page": { url: pageUrl },
		},
	});

	return pageUrl;
}
